### ISSUE TITLE
Function proposal - flatMapValues()

### ISSUE THREAD

**Issue by glenveegee** [jmespath/jmespath.jep#6]
For objects, it's currently very difficult (if not impossible) to have access to the key and the value in the same scope of the expression. This function would decompose objects into Array<[key:value]> such that every key corresponds to a decomposed value.

In javascript (typescript) this might look something like:

```javascript

registerFunction(
  'flatMapValues',
  ([inputObject]) => {
    return Object.entries(inputObject).reduce((flattened, entry) => {
      const [key, value]: [string, any] = entry;
      if (Array.isArray(value)) {
        return [...flattened, ...value.map(v => [key, v])];
      }
      return [...flattened, [key, value]];
    }, [] as any[]);
  },
  [{ types: [TYPE_OBJECT, TYPE_ARRAY] }],
);
```
Which produces the following:

```javascript
jmespath.search( { a: [1, 3, 5], b: [2, 4, 6] }, "flatMapValues(@)")
// OUTPUTS: [
//      ['a', 1],
//      ['a', 3],
//      ['a', 5],
//      ['b', 2],
//      ['b', 4],
//      ['b', 6],
//    ]

jmespath.search({ a: [true, { x: 3 }, null, 1234, ['XXX']], b: { x: 2 } }, "flatMapValues(@)")
// OUTPUTS: [
//      ['a', true],
//      ['a', { x: 3 }],
//      ['a', null],
//      ['a', 1234],
//      ['a', ['XXX']],
//      ['b', { x: 2 }],
//    ]

jmespath.search([ [1, 3, 5], [2, 4, 6] ], "flatMapValues(@)")
// OUTPUTS: [
//      ['0', 1],
//      ['0', 3],
//      ['0', 5],
//      ['1', 2],
//      ['1', 4],
//      ['1', 6],
//    ]

```
These could then be piped to expressions that filter on keys or project keys into new objects/arrays

**Comment by innovate-invent** [comment]
Could this be done with the proposed [let()](https://github.com/jmespath/jmespath.site/pull/6) function? I like this proposal but it could potentially violate the "one way of doing things" policy that has kept JMESPath simple.

**Comment by glenveegee** [comment]
This and an entire class of other proposed functions would definitely be supported by the let function. JEP 11: The let() Function is a great proposal as it generalises this core issue proposed here. Given it was proposed in 2015 I really hope there will be some progress on it.
